/**
 * Curated Lucide icon library for the admin picker.
 *
 * We explicitly import ~260 icons instead of the entire Lucide bundle so that
 * only these get shipped to the browser (tree shaking). Each icon is keyed by
 * its kebab-case name so values can be stored in the DB as simple strings
 * (e.g. "banknote", "graduation-cap").
 *
 * Organized by category so the picker can render tabs/sections naturally.
 */
import type { FunctionalComponent, SVGAttributes } from 'vue'
import {
  // Business & finance
  Briefcase,
  Building,
  Building2,
  Banknote,
  Wallet,
  CreditCard,
  Coins,
  PiggyBank,
  Receipt,
  DollarSign,
  Euro,
  Landmark,
  TrendingUp,
  TrendingDown,
  LineChart,
  BarChart,
  BarChart2,
  BarChart3,
  PieChart,
  Target,
  Trophy,
  Medal,
  Award,
  Crown,
  Gem,
  // Healthcare & wellness
  Heart,
  HeartPulse,
  Stethoscope,
  Pill,
  Activity,
  Ambulance,
  Cross,
  Microscope,
  Syringe,
  Dna,
  Shield,
  ShieldCheck,
  // Education & learning
  GraduationCap,
  BookOpen,
  Book,
  BookMarked,
  Library,
  Backpack,
  Pencil,
  PenTool,
  NotebookPen,
  // Tech & AI
  Cpu,
  Bot,
  BrainCircuit,
  Code,
  Code2,
  Terminal,
  Server,
  HardDrive,
  Database,
  Network,
  Wifi,
  Cloud,
  CloudUpload,
  CloudDownload,
  Plug,
  Key,
  Lock,
  Unlock,
  Smartphone,
  Laptop,
  Monitor,
  Tablet,
  // Industry & manufacturing
  Factory,
  Cog,
  Wrench,
  Hammer,
  HardHat,
  Truck,
  Package,
  PackageOpen,
  Boxes,
  Forklift,
  ConstructionIcon,
  // Transport & logistics
  Plane,
  Ship,
  Train,
  Car,
  Bus,
  Bike,
  Rocket,
  Map,
  MapPin,
  Navigation,
  Compass,
  Route,
  Globe,
  Globe2,
  // Energy & environment
  Zap,
  BatteryCharging,
  Flame,
  Leaf,
  Trees,
  Sun,
  Moon,
  CloudRain,
  Wind,
  Droplets,
  Sprout,
  // Government & legal
  Scale,
  Gavel,
  Vote,
  Flag,
  Stamp,
  FileSignature,
  BookCheck,
  // Retail & hospitality
  ShoppingCart,
  ShoppingBag,
  Store,
  Tags,
  Tag,
  Gift,
  Utensils,
  UtensilsCrossed,
  Coffee,
  Wine,
  Pizza,
  Hotel,
  BedDouble,
  // Real estate
  Home,
  HomeIcon,
  Warehouse,
  Building2 as Building2Alt,
  // Agriculture & food
  Wheat,
  TreePine,
  Tractor,
  Apple,
  Carrot,
  // Media & creative
  Film,
  Camera,
  CameraOff,
  Image,
  ImagePlus,
  Palette,
  Paintbrush,
  PaintBucket,
  Music,
  Music2,
  Music3,
  Headphones,
  Mic,
  Video,
  // Communication
  Mail,
  MailOpen,
  Send,
  MessageCircle,
  MessageSquare,
  MessagesSquare,
  Phone,
  PhoneCall,
  PhoneIncoming,
  PhoneOutgoing,
  Megaphone,
  Speaker,
  Radio,
  Bell,
  BellRing,
  // People & HR
  User,
  UserCheck,
  UserPlus,
  Users,
  UsersRound,
  UserCog,
  Contact,
  IdCard,
  BadgeCheck,
  // Content & documents
  FileText,
  File,
  FileCheck,
  FilePlus,
  FileX,
  FolderOpen,
  Folder,
  FolderPlus,
  FolderTree,
  Archive,
  Inbox,
  Paperclip,
  Clipboard,
  ClipboardCheck,
  ClipboardList,
  StickyNote,
  // UI actions
  Plus,
  PlusCircle,
  Minus,
  MinusCircle,
  X,
  XCircle,
  Check,
  CheckCircle,
  CheckCircle2,
  Search,
  Filter,
  SlidersHorizontal,
  RefreshCw,
  RotateCcw,
  Save,
  Upload,
  Download,
  Share2,
  Link,
  Link2,
  ExternalLink,
  Copy,
  Scissors,
  Trash,
  Trash2,
  Edit,
  Edit2,
  Edit3,
  Eye,
  EyeOff,
  Settings,
  Settings2,
  Sliders,
  // Analytics & charts
  PieChart as PieChartAlt,
  Gauge,
  Percent,
  Calculator,
  // Navigation & layout
  Menu,
  LayoutDashboard,
  LayoutGrid,
  LayoutList,
  Grid3x3,
  List,
  ArrowLeft,
  ArrowRight,
  GripVertical,
  ArrowUp,
  ArrowDown,
  ChevronLeft,
  ChevronRight,
  ChevronUp,
  ChevronDown,
  // Time
  Calendar,
  CalendarDays,
  CalendarCheck,
  Clock,
  Timer,
  AlarmClock,
  Hourglass,
  // Sports & lifestyle
  Dumbbell,
  Bike as BikeIcon,
  Activity as ActivityIcon,
  // Security
  KeyRound,
  Fingerprint,
  ShieldAlert,
  LockKeyhole,
  // Weather
  CloudSun,
  Snowflake,
  // Misc
  Lightbulb,
  Sparkles,
  Star,
  Bookmark,
  MapPinned,
  Puzzle,
  Layers,
  Boxes as BoxesIcon,
  Shapes,
  Pin,
  HelpCircle,
  Info,
  AlertCircle,
  AlertTriangle,
  Ban,
  // Social platforms
  Linkedin,
  Twitter,
  Facebook,
  Instagram,
  Youtube,
  Github,
  Dribbble,
  Twitch,
  Figma,
  Slack,
  Rss,
  AtSign,
  // Additional entity icons
  Handshake,
} from 'lucide-vue-next'

export type LucideIconComponent = FunctionalComponent<SVGAttributes>

export interface IconDefinition {
  name: string
  component: LucideIconComponent
  category: string
  keywords?: string[]
}

/**
 * Main icon library. Keys are kebab-case names that can be stored in the DB
 * and resolved back to a Lucide component via `iconLibrary[name]`.
 */
export const iconLibrary: Record<string, IconDefinition> = {
  // Business & finance
  'briefcase': { name: 'briefcase', component: Briefcase, category: 'Business', keywords: ['work', 'job', 'office'] },
  'handshake': { name: 'handshake', component: Handshake, category: 'Business', keywords: ['partner', 'deal', 'agreement'] },
  'building': { name: 'building', component: Building, category: 'Business', keywords: ['office', 'company'] },
  'building-2': { name: 'building-2', component: Building2, category: 'Business', keywords: ['corporate', 'headquarters'] },
  'banknote': { name: 'banknote', component: Banknote, category: 'Finance', keywords: ['money', 'cash', 'bank'] },
  'wallet': { name: 'wallet', component: Wallet, category: 'Finance', keywords: ['money', 'purse'] },
  'credit-card': { name: 'credit-card', component: CreditCard, category: 'Finance', keywords: ['payment', 'card'] },
  'coins': { name: 'coins', component: Coins, category: 'Finance', keywords: ['money', 'currency'] },
  'piggy-bank': { name: 'piggy-bank', component: PiggyBank, category: 'Finance', keywords: ['savings', 'money'] },
  'receipt': { name: 'receipt', component: Receipt, category: 'Finance', keywords: ['invoice', 'bill'] },
  'dollar-sign': { name: 'dollar-sign', component: DollarSign, category: 'Finance', keywords: ['money', 'usd'] },
  'euro': { name: 'euro', component: Euro, category: 'Finance', keywords: ['money', 'eur'] },
  'landmark': { name: 'landmark', component: Landmark, category: 'Finance', keywords: ['bank', 'government', 'institution'] },
  'trending-up': { name: 'trending-up', component: TrendingUp, category: 'Analytics', keywords: ['growth', 'rise'] },
  'trending-down': { name: 'trending-down', component: TrendingDown, category: 'Analytics', keywords: ['decline', 'fall'] },
  'line-chart': { name: 'line-chart', component: LineChart, category: 'Analytics', keywords: ['graph', 'data'] },
  'bar-chart': { name: 'bar-chart', component: BarChart, category: 'Analytics', keywords: ['graph', 'data'] },
  'bar-chart-2': { name: 'bar-chart-2', component: BarChart2, category: 'Analytics', keywords: ['graph'] },
  'bar-chart-3': { name: 'bar-chart-3', component: BarChart3, category: 'Analytics', keywords: ['graph'] },
  'pie-chart': { name: 'pie-chart', component: PieChart, category: 'Analytics', keywords: ['graph', 'data'] },
  'gauge': { name: 'gauge', component: Gauge, category: 'Analytics', keywords: ['meter', 'speedometer'] },
  'percent': { name: 'percent', component: Percent, category: 'Analytics', keywords: ['percentage'] },
  'calculator': { name: 'calculator', component: Calculator, category: 'Analytics', keywords: ['math', 'numbers'] },
  'target': { name: 'target', component: Target, category: 'Business', keywords: ['goal', 'aim'] },
  'trophy': { name: 'trophy', component: Trophy, category: 'Business', keywords: ['winner', 'award'] },
  'medal': { name: 'medal', component: Medal, category: 'Business', keywords: ['award', 'prize'] },
  'award': { name: 'award', component: Award, category: 'Business', keywords: ['prize', 'badge'] },
  'crown': { name: 'crown', component: Crown, category: 'Business', keywords: ['premium', 'royal'] },
  'gem': { name: 'gem', component: Gem, category: 'Business', keywords: ['diamond', 'premium'] },

  // Healthcare
  'heart': { name: 'heart', component: Heart, category: 'Healthcare', keywords: ['love', 'health'] },
  'heart-pulse': { name: 'heart-pulse', component: HeartPulse, category: 'Healthcare', keywords: ['health', 'medical'] },
  'stethoscope': { name: 'stethoscope', component: Stethoscope, category: 'Healthcare', keywords: ['doctor', 'medical'] },
  'pill': { name: 'pill', component: Pill, category: 'Healthcare', keywords: ['medicine', 'drug'] },
  'activity': { name: 'activity', component: Activity, category: 'Healthcare', keywords: ['pulse', 'heartbeat'] },
  'ambulance': { name: 'ambulance', component: Ambulance, category: 'Healthcare', keywords: ['emergency'] },
  'cross': { name: 'cross', component: Cross, category: 'Healthcare', keywords: ['medical', 'clinic'] },
  'microscope': { name: 'microscope', component: Microscope, category: 'Healthcare', keywords: ['science', 'research'] },
  'syringe': { name: 'syringe', component: Syringe, category: 'Healthcare', keywords: ['injection', 'vaccine'] },
  'dna': { name: 'dna', component: Dna, category: 'Healthcare', keywords: ['genetics', 'biology'] },

  // Education
  'graduation-cap': { name: 'graduation-cap', component: GraduationCap, category: 'Education', keywords: ['school', 'university'] },
  'book-open': { name: 'book-open', component: BookOpen, category: 'Education', keywords: ['read', 'study'] },
  'book': { name: 'book', component: Book, category: 'Education', keywords: ['read', 'learn'] },
  'book-marked': { name: 'book-marked', component: BookMarked, category: 'Education', keywords: ['bookmark', 'read'] },
  'library': { name: 'library', component: Library, category: 'Education', keywords: ['books', 'study'] },
  'backpack': { name: 'backpack', component: Backpack, category: 'Education', keywords: ['school', 'bag'] },
  'pencil': { name: 'pencil', component: Pencil, category: 'Education', keywords: ['write', 'draw'] },
  'pen-tool': { name: 'pen-tool', component: PenTool, category: 'Education', keywords: ['design', 'write'] },
  'notebook-pen': { name: 'notebook-pen', component: NotebookPen, category: 'Education', keywords: ['journal', 'note'] },

  // Tech & AI
  'cpu': { name: 'cpu', component: Cpu, category: 'Technology', keywords: ['processor', 'chip', 'computer'] },
  'bot': { name: 'bot', component: Bot, category: 'Technology', keywords: ['ai', 'robot', 'automation'] },
  'brain-circuit': { name: 'brain-circuit', component: BrainCircuit, category: 'Technology', keywords: ['ai', 'ml', 'intelligence'] },
  'code': { name: 'code', component: Code, category: 'Technology', keywords: ['programming', 'dev'] },
  'code-2': { name: 'code-2', component: Code2, category: 'Technology', keywords: ['programming'] },
  'terminal': { name: 'terminal', component: Terminal, category: 'Technology', keywords: ['cli', 'command', 'shell'] },
  'server': { name: 'server', component: Server, category: 'Technology', keywords: ['hosting', 'backend'] },
  'hard-drive': { name: 'hard-drive', component: HardDrive, category: 'Technology', keywords: ['storage', 'disk'] },
  'database': { name: 'database', component: Database, category: 'Technology', keywords: ['data', 'storage'] },
  'network': { name: 'network', component: Network, category: 'Technology', keywords: ['connection', 'nodes'] },
  'wifi': { name: 'wifi', component: Wifi, category: 'Technology', keywords: ['wireless', 'internet'] },
  'cloud': { name: 'cloud', component: Cloud, category: 'Technology', keywords: ['storage', 'online'] },
  'cloud-upload': { name: 'cloud-upload', component: CloudUpload, category: 'Technology', keywords: ['upload'] },
  'cloud-download': { name: 'cloud-download', component: CloudDownload, category: 'Technology', keywords: ['download'] },
  'plug': { name: 'plug', component: Plug, category: 'Technology', keywords: ['connect', 'power'] },
  'key': { name: 'key', component: Key, category: 'Security', keywords: ['access', 'unlock'] },
  'key-round': { name: 'key-round', component: KeyRound, category: 'Security', keywords: ['access', 'unlock'] },
  'lock': { name: 'lock', component: Lock, category: 'Security', keywords: ['secure', 'private'] },
  'unlock': { name: 'unlock', component: Unlock, category: 'Security', keywords: ['open', 'access'] },
  'lock-keyhole': { name: 'lock-keyhole', component: LockKeyhole, category: 'Security', keywords: ['secure'] },
  'fingerprint': { name: 'fingerprint', component: Fingerprint, category: 'Security', keywords: ['biometric', 'identity'] },
  'shield': { name: 'shield', component: Shield, category: 'Security', keywords: ['protection'] },
  'shield-check': { name: 'shield-check', component: ShieldCheck, category: 'Security', keywords: ['verified'] },
  'shield-alert': { name: 'shield-alert', component: ShieldAlert, category: 'Security', keywords: ['warning'] },
  'smartphone': { name: 'smartphone', component: Smartphone, category: 'Technology', keywords: ['mobile', 'phone'] },
  'laptop': { name: 'laptop', component: Laptop, category: 'Technology', keywords: ['computer'] },
  'monitor': { name: 'monitor', component: Monitor, category: 'Technology', keywords: ['screen', 'display'] },
  'tablet': { name: 'tablet', component: Tablet, category: 'Technology', keywords: ['device'] },

  // Industry & manufacturing
  'factory': { name: 'factory', component: Factory, category: 'Industry', keywords: ['manufacturing', 'plant'] },
  'cog': { name: 'cog', component: Cog, category: 'Industry', keywords: ['gear', 'settings', 'mechanical'] },
  'wrench': { name: 'wrench', component: Wrench, category: 'Industry', keywords: ['tool', 'repair'] },
  'hammer': { name: 'hammer', component: Hammer, category: 'Industry', keywords: ['tool', 'build'] },
  'hard-hat': { name: 'hard-hat', component: HardHat, category: 'Industry', keywords: ['construction', 'worker'] },
  'truck': { name: 'truck', component: Truck, category: 'Logistics', keywords: ['delivery', 'shipping'] },
  'package': { name: 'package', component: Package, category: 'Logistics', keywords: ['box', 'shipping'] },
  'package-open': { name: 'package-open', component: PackageOpen, category: 'Logistics', keywords: ['unbox'] },
  'boxes': { name: 'boxes', component: Boxes, category: 'Logistics', keywords: ['warehouse', 'inventory'] },
  'forklift': { name: 'forklift', component: Forklift, category: 'Logistics', keywords: ['warehouse'] },
  'construction': { name: 'construction', component: ConstructionIcon, category: 'Industry', keywords: ['build'] },

  // Transport
  'plane': { name: 'plane', component: Plane, category: 'Transport', keywords: ['flight', 'travel'] },
  'ship': { name: 'ship', component: Ship, category: 'Transport', keywords: ['boat', 'sea'] },
  'train': { name: 'train', component: Train, category: 'Transport', keywords: ['rail'] },
  'car': { name: 'car', component: Car, category: 'Transport', keywords: ['vehicle', 'drive'] },
  'bus': { name: 'bus', component: Bus, category: 'Transport', keywords: ['vehicle'] },
  'bike': { name: 'bike', component: Bike, category: 'Transport', keywords: ['bicycle'] },
  'rocket': { name: 'rocket', component: Rocket, category: 'Transport', keywords: ['launch', 'space'] },
  'map': { name: 'map', component: Map, category: 'Location', keywords: ['navigation'] },
  'map-pin': { name: 'map-pin', component: MapPin, category: 'Location', keywords: ['pin', 'marker'] },
  'map-pinned': { name: 'map-pinned', component: MapPinned, category: 'Location', keywords: ['location'] },
  'navigation': { name: 'navigation', component: Navigation, category: 'Location', keywords: ['compass', 'direction'] },
  'compass': { name: 'compass', component: Compass, category: 'Location', keywords: ['direction'] },
  'route': { name: 'route', component: Route, category: 'Location', keywords: ['path', 'journey'] },
  'globe': { name: 'globe', component: Globe, category: 'Location', keywords: ['world', 'international'] },
  'globe-2': { name: 'globe-2', component: Globe2, category: 'Location', keywords: ['world'] },

  // Energy & environment
  'zap': { name: 'zap', component: Zap, category: 'Energy', keywords: ['electric', 'power'] },
  'battery-charging': { name: 'battery-charging', component: BatteryCharging, category: 'Energy', keywords: ['power'] },
  'flame': { name: 'flame', component: Flame, category: 'Energy', keywords: ['fire', 'hot'] },
  'leaf': { name: 'leaf', component: Leaf, category: 'Environment', keywords: ['eco', 'nature', 'green'] },
  'trees': { name: 'trees', component: Trees, category: 'Environment', keywords: ['forest', 'nature'] },
  'tree-pine': { name: 'tree-pine', component: TreePine, category: 'Environment', keywords: ['forest'] },
  'sprout': { name: 'sprout', component: Sprout, category: 'Environment', keywords: ['growth', 'nature'] },
  'sun': { name: 'sun', component: Sun, category: 'Environment', keywords: ['solar'] },
  'moon': { name: 'moon', component: Moon, category: 'Environment', keywords: ['night'] },
  'cloud-rain': { name: 'cloud-rain', component: CloudRain, category: 'Environment', keywords: ['weather'] },
  'cloud-sun': { name: 'cloud-sun', component: CloudSun, category: 'Environment', keywords: ['weather'] },
  'snowflake': { name: 'snowflake', component: Snowflake, category: 'Environment', keywords: ['cold', 'winter'] },
  'wind': { name: 'wind', component: Wind, category: 'Environment', keywords: ['weather'] },
  'droplets': { name: 'droplets', component: Droplets, category: 'Environment', keywords: ['water'] },

  // Government & legal
  'scale': { name: 'scale', component: Scale, category: 'Legal', keywords: ['justice', 'balance'] },
  'gavel': { name: 'gavel', component: Gavel, category: 'Legal', keywords: ['law', 'judge'] },
  'vote': { name: 'vote', component: Vote, category: 'Legal', keywords: ['election', 'ballot'] },
  'flag': { name: 'flag', component: Flag, category: 'Government', keywords: ['country', 'nation'] },
  'stamp': { name: 'stamp', component: Stamp, category: 'Legal', keywords: ['approval', 'seal'] },
  'file-signature': { name: 'file-signature', component: FileSignature, category: 'Legal', keywords: ['contract', 'sign'] },
  'book-check': { name: 'book-check', component: BookCheck, category: 'Legal', keywords: ['rules', 'compliance'] },

  // Retail & hospitality
  'shopping-cart': { name: 'shopping-cart', component: ShoppingCart, category: 'Retail', keywords: ['buy', 'store'] },
  'shopping-bag': { name: 'shopping-bag', component: ShoppingBag, category: 'Retail', keywords: ['purchase'] },
  'store': { name: 'store', component: Store, category: 'Retail', keywords: ['shop', 'retail'] },
  'tags': { name: 'tags', component: Tags, category: 'Retail', keywords: ['labels', 'categories'] },
  'tag': { name: 'tag', component: Tag, category: 'Retail', keywords: ['label', 'price'] },
  'gift': { name: 'gift', component: Gift, category: 'Retail', keywords: ['present'] },
  'utensils': { name: 'utensils', component: Utensils, category: 'Hospitality', keywords: ['food', 'restaurant'] },
  'utensils-crossed': { name: 'utensils-crossed', component: UtensilsCrossed, category: 'Hospitality', keywords: ['dining'] },
  'coffee': { name: 'coffee', component: Coffee, category: 'Hospitality', keywords: ['drink', 'cafe'] },
  'wine': { name: 'wine', component: Wine, category: 'Hospitality', keywords: ['drink'] },
  'pizza': { name: 'pizza', component: Pizza, category: 'Hospitality', keywords: ['food'] },
  'hotel': { name: 'hotel', component: Hotel, category: 'Hospitality', keywords: ['stay', 'accommodation'] },
  'bed-double': { name: 'bed-double', component: BedDouble, category: 'Hospitality', keywords: ['hotel', 'room'] },

  // Real estate
  'home': { name: 'home', component: Home, category: 'Real Estate', keywords: ['house', 'residence'] },
  'warehouse': { name: 'warehouse', component: Warehouse, category: 'Real Estate', keywords: ['storage', 'industrial'] },

  // Agriculture
  'wheat': { name: 'wheat', component: Wheat, category: 'Agriculture', keywords: ['grain', 'farm'] },
  'tractor': { name: 'tractor', component: Tractor, category: 'Agriculture', keywords: ['farm'] },
  'apple': { name: 'apple', component: Apple, category: 'Agriculture', keywords: ['fruit', 'food'] },
  'carrot': { name: 'carrot', component: Carrot, category: 'Agriculture', keywords: ['vegetable'] },

  // Media & creative
  'film': { name: 'film', component: Film, category: 'Media', keywords: ['movie', 'video'] },
  'camera': { name: 'camera', component: Camera, category: 'Media', keywords: ['photo'] },
  'image': { name: 'image', component: Image, category: 'Media', keywords: ['photo', 'picture'] },
  'image-plus': { name: 'image-plus', component: ImagePlus, category: 'Media', keywords: ['add photo'] },
  'palette': { name: 'palette', component: Palette, category: 'Media', keywords: ['color', 'art'] },
  'paintbrush': { name: 'paintbrush', component: Paintbrush, category: 'Media', keywords: ['art', 'design'] },
  'paint-bucket': { name: 'paint-bucket', component: PaintBucket, category: 'Media', keywords: ['color', 'fill'] },
  'music': { name: 'music', component: Music, category: 'Media', keywords: ['sound', 'audio'] },
  'music-2': { name: 'music-2', component: Music2, category: 'Media', keywords: ['sound'] },
  'headphones': { name: 'headphones', component: Headphones, category: 'Media', keywords: ['audio', 'listen'] },
  'mic': { name: 'mic', component: Mic, category: 'Media', keywords: ['microphone', 'voice'] },
  'video': { name: 'video', component: Video, category: 'Media', keywords: ['camera', 'record'] },

  // Communication
  'mail': { name: 'mail', component: Mail, category: 'Communication', keywords: ['email', 'message'] },
  'mail-open': { name: 'mail-open', component: MailOpen, category: 'Communication', keywords: ['email', 'read'] },
  'send': { name: 'send', component: Send, category: 'Communication', keywords: ['submit'] },
  'message-circle': { name: 'message-circle', component: MessageCircle, category: 'Communication', keywords: ['chat'] },
  'message-square': { name: 'message-square', component: MessageSquare, category: 'Communication', keywords: ['chat'] },
  'messages-square': { name: 'messages-square', component: MessagesSquare, category: 'Communication', keywords: ['chat'] },
  'phone': { name: 'phone', component: Phone, category: 'Communication', keywords: ['call'] },
  'phone-call': { name: 'phone-call', component: PhoneCall, category: 'Communication', keywords: ['calling'] },
  'megaphone': { name: 'megaphone', component: Megaphone, category: 'Communication', keywords: ['announce'] },
  'speaker': { name: 'speaker', component: Speaker, category: 'Communication', keywords: ['sound'] },
  'radio': { name: 'radio', component: Radio, category: 'Communication', keywords: ['broadcast'] },
  'bell': { name: 'bell', component: Bell, category: 'Communication', keywords: ['notification'] },
  'bell-ring': { name: 'bell-ring', component: BellRing, category: 'Communication', keywords: ['alert'] },

  // People
  'user': { name: 'user', component: User, category: 'People', keywords: ['person', 'profile'] },
  'user-check': { name: 'user-check', component: UserCheck, category: 'People', keywords: ['verified'] },
  'user-plus': { name: 'user-plus', component: UserPlus, category: 'People', keywords: ['add', 'invite'] },
  'users': { name: 'users', component: Users, category: 'People', keywords: ['team', 'group'] },
  'users-round': { name: 'users-round', component: UsersRound, category: 'People', keywords: ['team'] },
  'user-cog': { name: 'user-cog', component: UserCog, category: 'People', keywords: ['settings', 'profile'] },
  'contact': { name: 'contact', component: Contact, category: 'People', keywords: ['address book'] },
  'id-card': { name: 'id-card', component: IdCard, category: 'People', keywords: ['badge', 'identity'] },
  'badge-check': { name: 'badge-check', component: BadgeCheck, category: 'People', keywords: ['verified'] },

  // Content & documents
  'file-text': { name: 'file-text', component: FileText, category: 'Documents', keywords: ['doc'] },
  'file': { name: 'file', component: File, category: 'Documents', keywords: ['document'] },
  'file-check': { name: 'file-check', component: FileCheck, category: 'Documents', keywords: ['approved'] },
  'file-plus': { name: 'file-plus', component: FilePlus, category: 'Documents', keywords: ['new'] },
  'folder': { name: 'folder', component: Folder, category: 'Documents', keywords: ['directory'] },
  'folder-open': { name: 'folder-open', component: FolderOpen, category: 'Documents', keywords: ['directory'] },
  'folder-plus': { name: 'folder-plus', component: FolderPlus, category: 'Documents', keywords: ['new folder'] },
  'folder-tree': { name: 'folder-tree', component: FolderTree, category: 'Documents', keywords: ['hierarchy'] },
  'archive': { name: 'archive', component: Archive, category: 'Documents', keywords: ['storage'] },
  'inbox': { name: 'inbox', component: Inbox, category: 'Documents', keywords: ['messages'] },
  'paperclip': { name: 'paperclip', component: Paperclip, category: 'Documents', keywords: ['attachment'] },
  'clipboard': { name: 'clipboard', component: Clipboard, category: 'Documents', keywords: ['notes'] },
  'clipboard-check': { name: 'clipboard-check', component: ClipboardCheck, category: 'Documents', keywords: ['done'] },
  'clipboard-list': { name: 'clipboard-list', component: ClipboardList, category: 'Documents', keywords: ['list'] },
  'sticky-note': { name: 'sticky-note', component: StickyNote, category: 'Documents', keywords: ['note'] },

  // Actions
  'copy': { name: 'copy', component: Copy, category: 'Actions', keywords: ['duplicate', 'clone'] },
  'trash': { name: 'trash', component: Trash, category: 'Actions', keywords: ['delete', 'remove'] },
  'trash-2': { name: 'trash-2', component: Trash2, category: 'Actions', keywords: ['delete', 'remove'] },
  'edit': { name: 'edit', component: Edit, category: 'Actions', keywords: ['modify', 'update'] },
  'eye': { name: 'eye', component: Eye, category: 'Actions', keywords: ['view', 'visible'] },
  'eye-off': { name: 'eye-off', component: EyeOff, category: 'Actions', keywords: ['hide', 'invisible'] },
  'save': { name: 'save', component: Save, category: 'Actions', keywords: ['disk', 'store'] },
  'upload': { name: 'upload', component: Upload, category: 'Actions', keywords: ['send'] },
  'download': { name: 'download', component: Download, category: 'Actions', keywords: ['receive'] },

  // Time
  'calendar': { name: 'calendar', component: Calendar, category: 'Time', keywords: ['date'] },
  'calendar-days': { name: 'calendar-days', component: CalendarDays, category: 'Time', keywords: ['date'] },
  'calendar-check': { name: 'calendar-check', component: CalendarCheck, category: 'Time', keywords: ['scheduled'] },
  'clock': { name: 'clock', component: Clock, category: 'Time', keywords: ['time'] },
  'timer': { name: 'timer', component: Timer, category: 'Time', keywords: ['stopwatch'] },
  'alarm-clock': { name: 'alarm-clock', component: AlarmClock, category: 'Time', keywords: ['alert'] },
  'hourglass': { name: 'hourglass', component: Hourglass, category: 'Time', keywords: ['wait'] },

  // Sports & lifestyle
  'dumbbell': { name: 'dumbbell', component: Dumbbell, category: 'Lifestyle', keywords: ['gym', 'fitness'] },

  // Social platforms
  'linkedin': { name: 'linkedin', component: Linkedin, category: 'Social', keywords: ['professional', 'network'] },
  'twitter': { name: 'twitter', component: Twitter, category: 'Social', keywords: ['x', 'tweet'] },
  'facebook': { name: 'facebook', component: Facebook, category: 'Social', keywords: ['meta', 'fb'] },
  'instagram': { name: 'instagram', component: Instagram, category: 'Social', keywords: ['photo', 'ig'] },
  'youtube': { name: 'youtube', component: Youtube, category: 'Social', keywords: ['video', 'yt'] },
  'github': { name: 'github', component: Github, category: 'Social', keywords: ['code', 'dev', 'git'] },
  'dribbble': { name: 'dribbble', component: Dribbble, category: 'Social', keywords: ['design', 'portfolio'] },
  'twitch': { name: 'twitch', component: Twitch, category: 'Social', keywords: ['streaming', 'video'] },
  'figma': { name: 'figma', component: Figma, category: 'Social', keywords: ['design', 'ui'] },
  'slack': { name: 'slack', component: Slack, category: 'Social', keywords: ['chat', 'workspace'] },
  'rss': { name: 'rss', component: Rss, category: 'Social', keywords: ['feed', 'blog'] },
  'at-sign': { name: 'at-sign', component: AtSign, category: 'Social', keywords: ['email', 'mention'] },

  // Misc
  'lightbulb': { name: 'lightbulb', component: Lightbulb, category: 'Misc', keywords: ['idea', 'insight'] },
  'sparkles': { name: 'sparkles', component: Sparkles, category: 'Misc', keywords: ['magic', 'ai'] },
  'star': { name: 'star', component: Star, category: 'Misc', keywords: ['favorite', 'rating'] },
  'bookmark': { name: 'bookmark', component: Bookmark, category: 'Misc', keywords: ['save'] },
  'puzzle': { name: 'puzzle', component: Puzzle, category: 'Misc', keywords: ['solution'] },
  'layers': { name: 'layers', component: Layers, category: 'Misc', keywords: ['stack'] },
  'shapes': { name: 'shapes', component: Shapes, category: 'Misc', keywords: ['geometry'] },
  'pin': { name: 'pin', component: Pin, category: 'Misc', keywords: ['attach'] },
  'help-circle': { name: 'help-circle', component: HelpCircle, category: 'Misc', keywords: ['question'] },
  'info': { name: 'info', component: Info, category: 'Misc', keywords: ['information'] },

  // Interface primitives
  'plus': { name: 'plus', component: Plus, category: 'Actions', keywords: ['add', 'new'] },
  'check': { name: 'check', component: Check, category: 'Actions', keywords: ['done', 'confirm'] },
  'arrow-left': { name: 'arrow-left', component: ArrowLeft, category: 'Actions', keywords: ['back'] },
  'arrow-right': { name: 'arrow-right', component: ArrowRight, category: 'Actions', keywords: ['forward'] },
  'grip-vertical': { name: 'grip-vertical', component: GripVertical, category: 'Actions', keywords: ['drag', 'reorder', 'handle'] },
  'chevron-up': { name: 'chevron-up', component: ChevronUp, category: 'Actions', keywords: ['collapse', 'up'] },
  'chevron-down': { name: 'chevron-down', component: ChevronDown, category: 'Actions', keywords: ['expand', 'down'] },
}

/**
 * Aliases map legacy / alternative icon names to the canonical Lucide key.
 * Extend this when you find stored values in the DB that predate the picker.
 */
const iconAliases: Record<string, string> = {
  'certificate': 'award',
  'trophy': 'award',
  'building-columns': 'landmark',
  'bank': 'landmark',
  'hospital': 'cross',
  'truck-moving': 'truck',
  'graduation': 'graduation-cap',
  'chart-line': 'line-chart',
  'chart-bar': 'bar-chart',
  'chart-pie': 'pie-chart',
  'cog-wheel': 'cog',
  'gear': 'cog',
  'settings': 'settings',
  'light-bulb': 'lightbulb',
  'light-ful': 'lightbulb',
  'user-group': 'users',
  'users-group': 'users',
  'house': 'home',
  'location': 'map-pin',
  'location-pin': 'map-pin',
  'clock-o': 'clock',
  'cloud-upload-alt': 'cloud-upload',
  'phone-alt': 'phone',
  'envelope': 'mail',
  'email': 'mail',
  // Social aliases
  'x': 'twitter',
  'x-twitter': 'twitter',
  'meta': 'facebook',
  'fb': 'facebook',
  'ig': 'instagram',
  'yt': 'youtube',
  'gh': 'github',
  'git': 'github',
  'in': 'linkedin',
  'linked-in': 'linkedin',
  'tiktok': 'music',
  'discord': 'messages-square',
  'whatsapp': 'message-circle',
  'telegram': 'send',
  'mastodon': 'at-sign',
  'threads': 'at-sign',
}

/** Ordered list of all icons for rendering in the picker. */
export const iconList: IconDefinition[] = Object.values(iconLibrary)

/** All unique categories, ordered. */
export const iconCategories: string[] = Array.from(
  new Set(iconList.map((icon) => icon.category)),
).sort()

/** Get an icon definition by its kebab-case name. Returns null if not found. */
export const getIcon = (name: string | null | undefined): IconDefinition | null => {
  if (!name) return null
  const direct = iconLibrary[name]
  if (direct) return direct
  const alias = iconAliases[name]
  if (alias && iconLibrary[alias]) return iconLibrary[alias]
  return null
}
